# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(max_length=30)),
                ('environment', models.CharField(max_length=30)),
                ('interface', models.CharField(max_length=30)),
                ('testcase', models.CharField(max_length=30)),
                ('status', models.CharField(default='waiting', max_length=30)),
                ('log_file', models.CharField(max_length=30, null=True)),
                ('fail', models.CharField(max_length=30, null=True)),
                ('success', models.CharField(max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
